function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1,YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 20-Aug-2015 12:59:01

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1,...
    'YTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 1],...
    'YGrid','on',...
    'XTick',[0 0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1 1],...
    'XGrid','on',...
    'Position',[0.0764840182648402 0.116781157998037 0.899543378995431 0.858267909715394],...
    'FontSize',34,...
    'FontName','Calibri');
%% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 1]);
box(axes1,'on');
hold(axes1,'all');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'Parent',axes1,'LineWidth',4);
set(plot1(1),'DisplayName','Numerical Solution [10]');
set(plot1(2),'MarkerSize',15,'Marker','<','LineStyle','none',...
    'DisplayName','Proposed Closed Form',...
    'Color',[0 0 0]);

% Create xlabel
xlabel({'C_t'},'FontSize',34,'FontName','Calibri');

% Create ylabel
ylabel({'Maximum Reading Efficiency'},'FontSize',34,'FontName','Calibri');

% Create legend
legend1 = legend(axes1,'show');
set(legend1,...
    'Position',[0.700761138409101 0.858784440491369 0.293031566408576 0.115273775216138]);

